### PR TITLE
Alternate icon set for table feature

### PR DESCRIPTION
**Pull request by dtwist**
Includes:
 - Row, Col, Cell icons from https://github.com/ckeditor/ckeditor5-table/issues/1
 - Alternate Table icon with 3 x 3 grid to match the row/col/cell icons above
 - Merge/Unmerge toggle states in case they are wanted instead of cell drop-down once multi-cell selection is working

### CODE REVIEW

**Comment by jodator** [comment]
@dtwist I didn't notice that you push that PR to `t/1` sorry for braking it.

I'll update your PR after we close the https://github.com/ckeditor/ckeditor5-table/pull/10.

**Comment by dtwist** [comment]
No worries; let me know if it's easier to just create a new PR.

BTW, I've not received an email to sign a CLA.

**Comment by Reinmar** [comment]
cc @vokiel

**Comment by vokiel** [comment]
@dtwist your email is hidden on GH thus we couldn't deliver CLA request. Please leave as a note on https://ckeditor.com/contact/ so we'll have your real email address to send CLA request to.

**Comment by jodator** [comment]
@dtwist it would be nice of you actually to create a new PR :smiley: 

The `t/1` is not going to be rebased as `t/9` just got merged into master and I plan to put `t/1` on review tomorrow.

**Comment by dtwist** [comment]
@vokiel email sent.

@jodator NP; what branch should I open the PR on? I'm assuming I should still create my own `t/1` branch per the contribution guide?

**Comment by dtwist** [comment]
Closing, will open new PR

**Pull request closed without merging**
