### PR TITLE
i/6169: Enhance Table plugin icon

### PR DESCRIPTION
**Pull request by panr**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Enhanced Table plugin icon. See ckeditor/ckeditor5#6168

--
Related to: ckeditor/ckeditor5#6169
Master PR: ckeditor/ckeditor5-media-embed#95

### CODE REVIEW

**Comment by oleq** [comment]
Also, the new icon visually stands out as smaller than the rest. Use the "iconset" manual test in theme-lark to learn more.

**Comment by Reinmar** [comment]
I find the new proposed icons a bit worse than what we have currently. I don't understand why you proposed changing their size?

**Comment by panr** [comment]
> I find the new proposed icons a bit worse than what we have currently. I don't understand why you proposed changing their size?

Because right now some of the icons are out of the "overall rhythm". IMHO every icon should have the same height (or at least something around it for a better optical alignment)

**Comment by panr** [comment]
I'm closing the PR as I mention here https://github.com/ckeditor/ckeditor5/issues/6168

**Pull request closed without merging**
