### PR TITLE
T/99: Introduce images in tables.

### LINKED ISSUE #98: Cannot click-select image in table
Trying select image with mouse results in unexpected selection (does not change).

Using <kbd>tab</kbd> to move focus inside table does selects an image (after changes from #97).

### LINKED ISSUE #99: Add images (nested widgets) support in tables.
Follow-up for the #56 - currently there are some issues with widget in widget (images in tables):

- click select does not work
- ballon toolbar sometimes does not work
- pasted image behaves differently then converted from data - you can edit caption only for pasted
- fake selection sometimes is broken

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Introduce images in tables. Closes #99.

---

### Additional information

* Requires changes in
    * Widget: https://github.com/ckeditor/ckeditor5-widget/pull/62 (will resolve #98)
    * Engine: https://github.com/ckeditor/ckeditor5-engine/pull/1608
    * Image: https://github.com/ckeditor/ckeditor5-image/pull/262
    * BlockQuote: https://github.com/ckeditor/ckeditor5-block-quote/pull/29
* Constelation of branches is available in [CKEditor 5 branch](https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-table/99).

### CODE REVIEW

**Comment by J-Nagle** [comment]
Thank you very much for this. We really needed this feature (and actually expected it to be there by default). This pull request is now in production on our system.

However, when using the third party [Simple Image Upload plugin](https://github.com/pourquoi/ckeditor5-simple-upload), the toolbar image upload button is still disabled inside table cells. It was necessary for us to use this instead of CKFinder as the documentation for uploading that way was not available on the CKEditor website at that time. Is it possible for you to look into this issue before moving on? If it's a problem on their side, we will probably migrate to CKFinder.

**Comment by jodator** [comment]
>  Is it possible for you to look into this issue before moving on

Oh. Thanks for the review!
I'll create a PR for this in the image feature and update the PR descriptions.

Here is the update image feature: https://github.com/ckeditor/ckeditor5-image/pull/262.

**Comment by jodator** [comment]
peek 2018-12-13 11-20

**Comment by scofalik** [comment]
It looks like you forgot to mention that there is also a PR in block-quote :). I was writing a post that there are failing tests there :)

**Comment by jodator** [comment]
> It looks like you forgot to mention that there is also a PR in block-quote :). I was writing a post that there are failing tests there :)

Oh sorry. Fixing.

**Comment by dannybarinshtein** [comment]
This is exactly what i've been waiting for, thanks guys!

I am however running into an issue after migrating from the stable version of the table to the master in order to use this feature.

```
TypeError: i.for(...).elementToElement is not a function
    at zb.init (tableediting.js:91)
```

I am using the React Component - any ideas what could this be / if I missed a step?

Cheers

**Comment by J-Nagle** [comment]
@dannybarinshtein There was a significant refactor to CKEditor shortly following this change, found at https://github.com/ckeditor/ckeditor5-engine/pull/1613. If you pull the master versions of all the repositories you’re using mentioned in that PR, you should be able to build a version of the project that no longer causes a TypeError.

We ran into this only yesterday and that’s how we fixed it. The developers also informed us that there might be breaking changes between the last version and the next release.

**Comment by dannybarinshtein** [comment]
@J-Nagle Thanks for the answer J-Nagle, its still not liking me for some reason.

I am trying to create the most basic form of the table at the moment, my package is as follows:

`{
	"name": "@ckeditor/ckeditor5-build-classic",
	"version": "11.2.0",
	"description": "The classic editor build of CKEditor 5 – the best browser-based rich text editor.",
	"keywords": [
		"ckeditor5-build",
		"ckeditor",
		"ckeditor5",
		"ckeditor 5",
		"wysiwyg",
		"rich text",
		"editor",
		"html",
		"contentEditable",
		"editing",
		"operational transformation",
		"ot",
		"collaboration",
		"collaborative",
		"real-time",
		"framework"
	],
	"main": "./build/ckeditor.js",
	"files": [
		"build"
	],
	"devDependencies": {
		"@ckeditor/ckeditor5-adapter-ckfinder": "^10.0.4",
		"@ckeditor/ckeditor5-alignment": "^10.0.4",
		"@ckeditor/ckeditor5-autoformat": "^10.0.4",
		"@ckeditor/ckeditor5-basic-styles": "^10.1.0",
		"@ckeditor/ckeditor5-block-quote": "https://github.com/ckeditor/ckeditor5-block-quote.git#master",
		"@ckeditor/ckeditor5-ckfinder": "https://github.com/ckeditor/ckeditor5-ckfinder.git#master",
		"@ckeditor/ckeditor5-clipboard": "^10.0.4",
		"@ckeditor/ckeditor5-dev-utils": "^11.0.1",
		"@ckeditor/ckeditor5-dev-webpack-plugin": "^7.0.1",
		"@ckeditor/ckeditor5-easy-image": "^10.0.4",
		"@ckeditor/ckeditor5-editor-classic": "^11.0.2",
		"@ckeditor/ckeditor5-essentials": "^10.1.3",
		"@ckeditor/ckeditor5-font": "^10.0.4",
		"@ckeditor/ckeditor5-heading": "https://github.com/ckeditor/ckeditor5-heading.git#master",
		"@ckeditor/ckeditor5-highlight": "^10.0.4",
		"@ckeditor/ckeditor5-image": "https://github.com/ckeditor/ckeditor5-image.git#master",
		"@ckeditor/ckeditor5-link": "https://github.com/ckeditor/ckeditor5-link.git#master",
		"@ckeditor/ckeditor5-list": "https://github.com/ckeditor/ckeditor5-list.git#master",
		"@ckeditor/ckeditor5-media-embed": "https://github.com/ckeditor/ckeditor5-media-embed.git#master",
		"@ckeditor/ckeditor5-paragraph": "https://github.com/ckeditor/ckeditor5-paragraph.git#master",
		"@ckeditor/ckeditor5-paste-from-office": "^10.0.0",
		"@ckeditor/ckeditor5-table": "https://github.com/ckeditor/ckeditor5-table.git#master",
		"@ckeditor/ckeditor5-theme-lark": "^12.0.0",
		"@ckeditor/ckeditor5-upload": "^10.0.4",
		"eslint": "^5.5.0",
		"eslint-config-ckeditor5": "^1.0.7",
		"husky": "^0.14.3",
		"lint-staged": "^7.0.0",
		"postcss-loader": "^3.0.0",
		"raw-loader": "^1.0.0",
		"style-loader": "^0.23.0",
		"uglifyjs-webpack-plugin": "^1.2.7",
		"webpack": "^4.15.0",
		"webpack-cli": "^3.0.8"
	},
	"engines": {
		"node": ">=6.9.0",
		"npm": ">=3.0.0"
	},
	"author": "CKSource (http://cksource.com/)",
	"license": "GPL-2.0-or-later",
	"homepage": "https://ckeditor.com",
	"bugs": "https://github.com/ckeditor/ckeditor5-build-classic/issues",
	"repository": {
		"type": "git",
		"url": "https://github.com/ckeditor/ckeditor5-build-classic.git"
	},
	"scripts": {
		"build": "webpack --mode production",
		"lint": "eslint --quiet '**/*.js'",
		"precommit": "lint-staged",
		"preversion": "npm run build; if [ -n \"$(git status src/ckeditor.js build/ --porcelain)\" ]; then git add -u src/ckeditor.js build/ && git commit -m 'Internal: Build.'; fi"
	},
	"lint-staged": {
		"**/*.js": [
			"eslint --quiet"
		]
	},
	"eslintIgnore": [
		"build/**",
		"packages/**"
	],
	"dependencies": {
		"@ckeditor/ckeditor5-core": "https://github.com/ckeditor/ckeditor5-core.git#master",
		"@ckeditor/ckeditor5-engine": "https://github.com/ckeditor/ckeditor5-engine.git#master",
		"@ckeditor/ckeditor5-enter": "https://github.com/ckeditor/ckeditor5-enter.git#master",
		"@ckeditor/ckeditor5-typing": "https://github.com/ckeditor/ckeditor5-typing.git#master",
		"@ckeditor/ckeditor5-ui": "https://github.com/ckeditor/ckeditor5-ui.git#master",
		"@ckeditor/ckeditor5-undo": "https://github.com/ckeditor/ckeditor5-undo.git#master",
		"@ckeditor/ckeditor5-utils": "^11.1.0",
		"@ckeditor/ckeditor5-widget": "https://github.com/ckeditor/ckeditor5-widget.git#master"
	}
}
`

But I am getting the following error:

TypeError: t is not iterable
    at conversion.js:598
    at Object.add (conversion.js:152)
    at r_.init (tableediting.js:85)


Any thoughts or suggestions?

**Pull request merged**
