### PR TITLE
T/ckeditor5/1151: Adjusted `InsertTableView` for better compatibility with right–to–left (RTL) languages

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Adjusted `InsertTableView` for better compatibility with right–to–left (RTL) languages. See ckeditor/ckeditor5#1151.

---

### Additional information

A piece of https://github.com/ckeditor/ckeditor5/pull/1881.

### CODE REVIEW

**Comment by Reinmar** [comment]
I don't understand this change. Can you explain why spaces were bad?

**Comment by Reinmar** [comment]
There's also https://github.com/ckeditor/ckeditor5/issues/1151#issuecomment-515064624 which perhaps we can squeeze into this PR.

**Comment by oleq** [comment]
When you have a table let's say 2x5 (LTR) it is 2 rows and 5 columns. But when you enable RTL UI things go backwards and the label is displayed 5x2, which makes no sense. Maybe I should've used nbsp instead. I made this change at the beginning and didn't think it through.

> There's also ckeditor/ckeditor5#1151 (comment) which perhaps we can squeeze into this PR (if not, let's make it a followup for it27).

Follow–up.

**Comment by oleq** [comment]
Sorted out the label problem. Used the multiplication sign '×' instead of 'x' letter and it looks great now.

**Comment by Reinmar** [comment]
Interesting problem :D I didn't think about this at all.

**Pull request merged**
