### PR TITLE
Integrated multi cell selection with set column /row header commands

### PR DESCRIPTION
**Pull request by mlewand**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Type: Integrated multi cell selection with set column /row header commands. Closes ckeditor/ckeditor5#6127.

---

### Additional information

After this PR the header command state could get a third state - "mixed" because it's possible to make selection where only part of it contains headers:

However to simplify things, I implemented it in a way that command state is true only when all selected cells contain header. Otherwise it's `false`.

~I have based this PR on #266 as this PR adds the API that was useful for this enhancement.~ Rebased onto master, after #265 added API that I was mocking before.

### CODE REVIEW

**Comment by mlewand** [comment]
Rebased onto the latest `master` branch from after #265. @ckeditor/qa-team please give it a testing.

**Comment by mlewand** [comment]
Just pushed one missing commit, sorry for that :see\_no\_evil: @ckeditor/qa-team

**Comment by mlewand** [comment]
Merged latest master, resolved conflicts.

**Comment by FilipTokarski** [comment]
I'm not sure what is the desired behaviour here, but this cell splitting looks a bit weird:
  
### Safari
- ( please note how on Safari it changes whole selection, it stays on one cell in column d, under the balloon )
table_header_safari1


### Chrome:  
table_header_chrome1

**Comment by mlewand** [comment]
> I'm not sure what is the desired behaviour here, but this cell splitting looks a bit weird:

I believe that exactly the same behavior is present on `master` branch, right? Neither was I a fan of this, but here I focused on bringing support for multi select, not that much on fixing underlying table plugin logic.

**Comment by mlewand** [comment]
Merged the `master` branch and resolved conflicts.

**Pull request merged**
