### PR TITLE
t/200c: Column insertion and cell merging buttons should work correctly...

### LINKED ISSUE #200: [RTL] Make sure that insert column buttons work right
As in https://github.com/ckeditor/ckeditor5/issues/1151#issuecomment-515064624:

> No, I mean in the table itself. When "Insert column right", a left column inserted instead and vice versa.

A follow-up of https://github.com/ckeditor/ckeditor5/issues/1151.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Column insertion and cell merging buttons should work correctly when the editor content is right–to–left (RTL). Closes #200.

### CODE REVIEW

**Comment by scofalik** [comment]
Remember to test this with track changes ...

**Comment by oleq** [comment]
@scofalik The change is at the UI level. Could this affect TC?

**Comment by jodator** [comment]
Yeah - I think that this shouldn't affect TC from the model POV (I don't know what happens there on the UI level)

**Comment by oleq** [comment]
This is what it looks like in LTR now. It shouldn't be a big UI deal when it goes RTL.

image

BTW: Something's wrong with merging cells. It does not look like it does anything...

**Comment by scofalik** [comment]
I was afraid that after pressing "insert column left" the column would be inserted on the right or something. 👍

**Pull request merged**
